### ISSUE TITLE
make asset failed

### ISSUE THREAD

**Issue by zhangweiqaz** [1Panel-dev/webkubectl#51]
hi， please tell me how to compile the assert. I suffered below error when executed "make asset".  Which base build image I should use
ERROR in ./src/xterm.ts
(6,6): error TS2339: Property 'loadAddon' does not exist on type 'typeof 'xterm''.

ERROR in ./src/xterm.ts
(11,11): error TS2304: Cannot find name 'bare'.

ERROR in ./src/xterm.ts
(23,21): error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.

ERROR in ./src/xterm.ts
(11,11): error TS4031: Public property 'term' of exported class has or is using private name 'bare'.

**Comment by liqiang-fit2cloud** [comment]
try this https://github.com/1Panel-dev/webkubectl/commit/e8c8db8810cc9f58b358e22cc77af568942d2fb6

**Comment by zhangweiqaz** [comment]
It works，Thanks！
