### ISSUE TITLE
Install Packages (e.g., Git, sudo, curl etc) in Webkubectl

### ISSUE THREAD

**Issue by Meetsimar** [1Panel-dev/webkubectl#52]
I’m using Webkubectl to manage my Kubernetes cluster and I need to install various packages such as Git or sudo. Could you please provide guidance on how to install packages or tools within Webkubectl? If there are specific steps or commands required, please include those details.

**Comment by liqiang-fit2cloud** [comment]
Hi,
You can build your own docker image with below dockerfile.
```
FROM kubeoperator/webkubectl
RUN apk add --update --no-cache git or_any_other_packages
```
